# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "base"

  config.vm.provider :vmck do |provider|
    provider.vmck_url = 'http://127.0.0.1:8000'
  end

end
