# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "base"

  config.vm.provision 'hello', type: 'shell', inline: 'echo hello world'

  config.vm.provider :vmck do |provider|
    provider.vmck_url = ENV['VMCK_URL']
    provider.memory = 333
    provider.cpus = 1
  end

end
