# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "base"

  config.vm.provision 'hello', type: 'shell', inline: 'echo hello world'

  config.vm.provider :vmck do |vmck|
    vmck.image_path = 'imgbuild-master.qcow2.tar.gz'
    vmck.vmck_url = ENV['VMCK_URL']
    vmck.memory = 512
    vmck.cpus = 1
    vmck.usbstick = ENV['VMCK_USBSTICK']
  end

end
