# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-env")
    config.env.enable
  end

  config.vm.box = "base"

  config.vm.provision 'hello', type: 'shell', inline: 'echo hello world'

  config.vm.provider :vmck do |vmck|
    vmck.image_path = 'imgbuild-master.qcow2.tar.gz'
    vmck.vmck_url = ENV['VMCK_URL']
    vmck.memory = 512
    vmck.cpus = 1
    vmck.storage = ENV['VMCK_STORAGE']
    vmck.name = ENV['JOB_NAME']
  end

end
