Vagrant.configure("2") do |config|
    config.vm.box = 'base'

    if Vagrant.has_plugin?('vagrant-env')
        config.env.enable
    end

    config.nfs.functional = false

    config.vm.provider :vmck do |vmck|
        vmck.vmck_url = ENV['VMCK_URL']
    end
end
